---
name: Checks

on: [push]

jobs:
  test-lint: 
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-actionv@1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tests
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
      
